version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017/mydb

  db:
    image: mongo
    ports:
      - "27017:27017"
